MyHookie/hookie_front

- src/App.jsx
- src/pages/Welcome/index.jsx
- 스플래시 화면 이후 로그인을 하지 않았을 때 나오는 페이지입니다.
- pages 폴더에 Welcome 폴더 생성하여 작업했습니다.
- 버튼 눌렀을 때 이동하는 기능은 아직 추가 하지 않았습니다.
- 애니메이션 추가를 위해 추후 framer-motion 라이브러리 추가 예정입니다.
- 버튼 공통 컴포넌트에 백그라운드 컬러가 픽스 되어있었는데, 이메일로 로그인 버튼에만 다른 백그라운드 컬러로 인해 어떻게 이것만 변경할까에 대한 고민이 있었습니다.
- CSS 셀렉터를 이용하여 코드를 작성했는데 임시방편일 것 같은 생각이 들어서 좋은 코드 있으면 공유 부탁드립니다.
close : #12
> Welcome 페이지 퍼블리싱

- src/App.jsx
- src/components/Form/FormInput/index.jsx
- src/components/Form/SignUpForm/index.jsx
- src/components/Title/index.jsx
- src/pages/Auth/SignUp/index.jsx
- src/styles/GlobalStyle.js
- 피그마 디자인 시안대로 UI만 구현하였습니다.
- 인풋창 폼은 Form -> FormInput 폴더에 있으니 가져다 쓰시면 될 것 같습니다.
- 데이터 받아와서 기능 추가하면 코드 많이 변경 될 것 같습니다 😭
- 자동완성 시 webkit 브라우저에서 적용되는 배경색이 불필요하다 생각하여 글로벌 스타일에 제어하는 코드 추가
<div display='flex'>
</div>
close : #14
> 회원가입 페이지 퍼블리싱

- src/pages/Welcome/index.jsx
- 버튼 클릭하면 해당 페이지로 이동합니다.
- 처음 Link를 이용해서 구현했는데 useNavigate 훅 사용하는 것으로 수정하였습니다.
close : #19
> welcome 페이지 버튼 클릭 시 해당 페이지로 이동하는 기능 구현

- src/components/Post/PostItem/index.jsx
- src/components/Post/PostList/index.jsx
- src/components/Post/dummyList.js
- src/pages/Home/index.jsx
- src/styles/GlobalStyle.js
- Header과 Navigation에 부족한 부분이 있습니다.
- 아래 작업 예정
- Header sticky 속성 추가
- Background color 추가
- Bottom background color 추가
- bottom에 padding을 줘서 Navigation이 숨기는 내용이 없도록 함
close : #15
> 홈페이지 UI 구현

- src/pages/Post/PostUpload/index.jsx
- 첫 페이지
- 태그 입력, 후기 입력 시 보이는 페이지
close : #27
> 게시글 upload 페이지 UI 구현

- src/components/MessageInput/index.jsx
- src/components/MessageItem/index.jsx
- src/components/MessageItemYours/index.jsx
- src/components/common/ConfirmHeader/index.jsx
- src/pages/Chat/ChatDetail/index.jsx
- src/pages/Chat/index.jsx
- src/styles/GlobalStyle.js
- 채팅창 화면 구현 
- 공통 요소에 overflow-x : hidden 추가된 점 
- BaseHeader 이용했는데 혹시 충돌 날 수도 있을 듯합니다...! 
input 입력 
(전송 버튼 active시 active blue 컬러로 변경됨) 
close : #16
> Design/#16 채팅방 UI 구현 

- src/components/FormInput/index.jsx
- src/pages/Auth/SignUp/index.jsx
- 마크업 & 스타일
- 비밀번호 정규식 변경
- 영문, 숫자 포함하여 6~16자 ➡️ 영문, 숫자 포함하여 8자 이상
- 플레이스 홀더, 에러 메시지 문구 약간 수정
- 화살표로 표시한 부분 너비가 좀 넓어보이지 않나요? 좀만 붙이면 좋을지 논의 해보고싶습니다.
close : #47
> 에러 메시지 출력 CSS 마크업 수정

- src/components/ProfileImageInput/index.jsx
- src/components/ProfileImageInput/index.style.js
- src/pages/Auth/ProfileSetting/index.jsx
- src/pages/Auth/ProfileSetting/index.style.js
- 사진상에서 보더 컬러가 블루로 되어있는데 기능 들어가면 그레이 컬러 적용되는 부분입니다.
- 프로필 페이지 작업에서 스타일과 컴포넌트 파일 분리, 추후 다른 페이지들 분리 예정
close : #68
> 프로필 페이지 UI 구현

- public/index.html
- src/components/Modal/SnackBar/index.jsx
- src/components/Post/PostItem/index.jsx
- src/components/common/Navigation/NavigationLink/index.jsx
- src/components/common/Navigation/index.jsx
- 임의로 피그마대로 navigation ui를 변경했습니다. (이전이 좋다면 편하게 말씀해주세요 !)
- SnackBar에는 원하는 content(내용)만 전달해서 사용하시면 됩니다.
- 사용하실때에는 자동으로 사라질 수 있도록 setTimeout 로직이 필요합니다. 
Navigation 수정 전 디자인
Navigation 수정 후 디자인
SnackBar 적용 디자인
close : #91
> SnackBar 모달 구현, Navigation 기능 추가, 디자인 수정

- src/components/FollowItem/index.jsx
- src/pages/Profile/Follower/index.jsx
- src/pages/Profile/Following/index.jsx
- 팔로우/팔로잉페이지에서 다른 사람 프로필을 들어가도 내 팔로우/팔로잉이 보이는 오류 해결하기
- 자기 자신을 팔로우 하려고 할 때, 에러 메시지 띄우기
- 팔로우/팔로잉이 많아도 api에서 팔로우/팔로잉 리스트가 10개까지만 보여지게 해주네요...
close : #117
> 팔로우/팔로잉 페이지 오류 수정

- src/api/comment.js
- src/api/post.js
- src/components/Comment/CommentInput/index.jsx
- src/components/Comment/CommentItem/index.jsx
- src/components/Post/PostItem/index.jsx
- src/components/Post/PostItem/index.styles.js
- src/pages/Post/PostDetail/index.jsx
- 좋아요/댓글 수정/삭제가 새로고침 해야 반영되는 오류 수정
- 댓글을 다는 유저의 프로필이 없을 때, 액박 + 레이아웃 깨지는 오류 수정
- 댓글의 사용자 이름을 username으로 수정
- 게시글 삭제 > 홈으로 이동하도록 수정
- 프로필 페이지에서 게시글 삭제 > 프로필 페이지로 이동하도록 수정
이따가 올리겠습니다 ㅎㅎ
close : #118
> 게시글 상세 페이지 오류 수정

- src/components/Profile/MyPicks/MyPickItem/index.jsx
- src/components/Profile/MyPicks/MyPickModal/index.jsx
- src/components/Profile/MyPicks/MyPickModal/index.style.js
- src/components/Profile/MyPicks/index.jsx
- 상품 리스트 데이터를 공유해서 모달에도 넘겨줄까 하였으나 API 설계 의도에 맞게 모달 안에서 상품 디테일을 불러와서 처리하는 방향으로 
- 수정, 삭제 기능만 남은 상태 
- 윤철님 도움 감사합니다~~ 
close : #127
> myPick 모달 상세 내용 보기 구현

- src/components/Skeleton/Search/index.jsx
- src/components/UserSearch/index.jsx
- src/styles/Util.js
- network에서 인터넷 속도를 낮춰 측정하면 더 확실히 볼 수 있습니다.
close : #137
> 검색페이지 Loading Indicator 적용

- src/components/Profile/ProfilePost/index.jsx
- src/components/Profile/ProfilePost/index.styles.js
- src/components/Profile/UserInfo/index.jsx
- src/components/Profile/UserInfo/index.styles.js
- src/components/Skeleton/PostSkeleton/index.jsx
- src/pages/Auth/ProfileSetting/index.style.js
- src/pages/Home/index.jsx
- src/pages/Home/index.styles.js
- src/styles/Util.js
- 앨범형과 프로필 정보 로딩에 적용은 너무 과한느낌이어서 적용하지 않았습니다. (무한 스크롤 시 보여주기 용도이기 때문에)
close : #146
> 홈페이지, 프로필 페이지 Loading Indicator 적용

- src/App.jsx
- src/atoms/darkMode.js
- src/hooks/useTheme.js
- src/pages/Auth/ProfileSetting/index.style.js
- src/pages/Profile/index.jsx
- 모달 버튼을 누르면 다크모드, 라이트모드 설정
- 사용자 OS 설정에 따라 다크모드, 라이트모드 설정이 됩니다.
해결해야 할 것 
1. 사용자 OS에 따라 새로고침하면 모드 설정이 변경되는 현상  
사용자 OS가 다크모드이고 버튼을 눌러 라이트 모드로 했을 때 새로고침 하면 다크모드로 변경됨
2. 모달 버튼 텍스트 다크모드로 하드코딩 되어있어 토글 기능은 구현되나 모달을 벗어나면 다시 다크모드로 변경
3. 버튼 클릭한 뒤 모달 아웃되게하기
close : #151
> 다크모드, 라이트모드 토글 기능 구현

- src/components/MyPicks/MyPickModal/index.jsx
- src/components/MyPicks/index.jsx
- src/pages/MyPicks/MyPicksEdit/index.jsx
- src/pages/MyPicks/MyPicksUpload/index.jsx
- 바로 삭제 반영됩니다 
- useEffect로 모달 여닫힘 추적 리렌더링이나 간이로 useState 만들어서 강제 렌더링 방법 적용해봤는데 잘 작동하지 않아모달에 get요청을 넘겨주어서 setState가 다시 작동되는 방식으로 적용중입니다 !
https://user-images.githubusercontent.com/95897068/210208866-5d58f2bd-e1e1-47c2-8e20-626dc9371614.mov
close : #159
> myPick 삭제시 새로고침 해야 반영되는 오류 해결

- src/components/Post/PostItem/index.jsx
- src/components/Post/PostItem/index.styles.js
> 개행한 문자열이 포스트에서 보이지 않던 현상 해결

- src/pages/Post/PostDetail/index.jsx
- Detail Page에서 api로 댓글 호출할 경우 에러처리를 하지 않은 코드 수정
close : #179
> 옵셔널 체이닝으로 cannot read properties 오류 해결

- src/api/follow.js
- src/components/FollowItem/index.jsx
- src/pages/Profile/Follower/index.jsx
- src/pages/Profile/Following/index.jsx
> 팔로잉/팔로워 페이지 api 분리 및 모든 유저가 보이도록 구현

- src/components/Comment/CommentItem/index.jsx
> 댓글 클릭시 프로필 페이지 이동하도록 구현
