- src/components/Post/PostItem/index.jsx
- src/components/common/BaseHeader/index.jsx
- src/components/common/ConfirmHeader/index.jsx
- src/components/common/Navigation/index.jsx
- src/components/common/SearchHeader/index.jsx
- src/pages/Home/index.jsx
- Header가 존재하는 페이지에서 height가 100vh속성을 주는 경우
- height의 높이를 100+4.4(헤더 높이)로 설정해야함
- page에 Navigation이 있다면 margin-bottom 6rem(Nav 높이)만큼 추가해야함
close : #24
> Header, Navigation 부족한 속성 추가

- src/components/Comment/CommentInput/index.jsx
- src/components/Comment/CommentItem/index.jsx
- src/pages/Post/PostDetail/index.jsx
- 헤더 추가
- Post 컴포넌트 대체 요소 생성
- 댓글 입력 컴포넌트 구현
- 댓글 컴포넌트 구현
- 홈 페이지의 PostItem 수정 완료 후, 해당 페이지의 Post 컴포넌트 추가할 예정입니다.
- 아래로 스크롤하면 댓글 하단 여백 보입니다!
close : #25
> 게시글 상세 페이지 UI 마크업 초안 구현

- src/components/FollowerItem/dummyList.js
- src/components/FollowerItem/index.jsx
- src/pages/Profile/Follower/index.jsx
- 팔로워 아이템 컴포넌트 분리
- 팔로워 페이지 및 팔로워 아이템 마크업 수정
- 반응성을 고려하여 팔로워 아이템 마크업 수정
- 더미데이터 사용
close : #32
> 팔로워 페이지 UI 수정

- src/components/MessageItem/index.jsx
- src/components/MessageItemYours/index.jsx
- src/pages/404/index.jsx
- 404페이지 UI 구현
- 피그마상으로는 살짝 위로 배치되어있는데 가운데 정렬로 바꿨습니다.
- 다시는 이슈넘버를 빼먹지 않겠습니다. 
(화면이 늘어나도 문제없다구~)
close : #34
> Feature/#34 404 페이지 UI 

- src/components/Comment/CommentItem/index.jsx
- src/components/Post/PostItem/index.jsx
- src/pages/Post/PostDetail/index.jsx
- src/styles/GlobalStyle.js
- 홈 페이지에서 게시물 상세 페이지로 이동했을 때, 스크롤 위치가 매번 다른 것 같아서 항상 상단으로 올 수 있도록 나중에 기능 구현해보겠습니다!
close : #38
> 게시글 상세 페이지 UI 수정 및 모달창 기능 구현

- src/components/AuthInputForm/index.jsx
- src/pages/Auth/Login/index.jsx
- src/pages/Auth/SignUp/index.jsx
- 피그마 디자인 시안대로 UI 구현
- 디자인 작업 때문에 AuthInputForm에서 작성한 checkValid 함수가 <AuthInputForm /> 컴포넌트에 props로 inputValue를 주지 않으면 최초 랜더링 시 언디파인드 뿜어내서 에러로 인해 일단 옵셔널체이닝으로 임시방편 해놓았습니다.
-  checkValid 함수 기본 리턴값의 컬러가 ACTIVE_BLUE로 되어있어서 아무것도 입력하지 않았을 때 GRAY가 아닌 ACTIVE_BLUE 활성화
기능 구현하면서 수정해나갈 듯 합니다.
일단 디자인 보여주기 위한 gif
close : #50
> 로그인 페이지 UI 작업

- public/index.html
- src/components/Modal/BottomSheet/index.jsx
- src/components/Modal/Dialog/index.jsx
- src/components/Modal/index.jsx
- src/components/Post/PostItem/index.jsx
- Dialog 모달을 구현하고, post item에 적용해봤습니다.
- Dialog 닫는 로직 세부 사항
- Dialog 모달 취소 or 외부 클릭 시 Dialog 모달만 닫힘
- Dialog 모달 삭제 클릭 시 삭제에 관한 로직 실행 후 Dialog, Bottom sheet 모두 닫힘
- 현재 Dialog 모달의 버튼이 삭제,취소로 고정되어있는데, 쓰이는 곳에 따라 색상과 텍스트를 변경하면 됩니다.
- 모달을 사용하는 곳에서 거의 같은 코드들이 반복되는데, 나중에 같이 custom hook으로 만들어보는 작업을 해봅시다 !
close : #58
> Dialog 모달창 구현

- src/api/authAxios.js
- src/atoms/auth.js
- src/components/AuthInputForm/index.jsx
- src/pages/Auth/Login/index.jsx
- src/pages/Auth/SignUp/index.jsx
로그인 기능 일부 구현
- 이메일, 비밀번호 인풋 값 유무에 따른 버튼 활성화, 비활성화
- 로그인 버튼 눌렀을 때 로그인 api 통신 후 이메일과 비밀번호 유효성 검사 진행
- 유효성 검사에 따른 에러 메시지 출력
- 통과하면 홈 페이지로 이동
- 최초 렌더링, 에러메시지 출력 후 인풋에 포커스 되도록
- post 요청만 한 상태이고 받은 데이터 가공할 차례입니다.
- 회원가입 후에 페이지를 profile로 가게 했는데 수정할 예정입니다.
- 코드가 노클린..
close : #52
> 로그인 페이지 기능구현

- src/components/Comment/CommentInput/index.jsx
- src/components/Comment/CommentItem/index.jsx
- src/pages/Post/PostDetail/index.jsx
- 뒤로가기 아이콘을 클릭했을 때, 홈 화면으로 이동
- 사용자의 댓글 입력 여부에 따라 '게시' 버튼의 색상 변경
- 댓글 내용이 길어졌을 때 개행
- 댓글을 입력했을 때 내용이 길어지면 개행
- 댓글 작성/삭제는 api 통신 시작할 때 다시 구현할 예정 입니다...! 그때 DOM 조작 방법을 useRef로 사용해볼게요!
- 댓글에서 엔터키를 누르면 textarea에 스크롤이 생겨 긴 내용을 확인할 수 있습니다.
close : #55
> 게시물 상세 페이지 세부 기능 구현

- src/components/UserSearch/SearchedUser/index.jsx
- src/components/UserSearch/index.jsx
- src/components/common/SearchHeader/index.jsx
- 검색 가능
- username과 accountname으로 검색이 가능하지만 보이는건 username뿐입니다. 
- accountname을 intro로 대체
- 원래 input 검색 내용과 username이 동일하다면 하이라이팅 처리를 하려했는데 지금은 해도 될지 모르겠네요
- 예를 들어 test를 입력했는데 username은 유저이고 accountname이 test인 사람인 경우 검색 내용도 존재하지 않고 하이라이팅도 안됐는데 검색되는 일이 발생 할듯합니다.
close : #71
> 유저 검색 컴포넌트 UI 구현, 검색 API 로직 작성

- src/App.jsx
- src/pages/Mypicks/index.jsx
- src/pages/Mypicks/index.style.js
- 헤더 뒤로가기 및 저장 버튼 누르면 Dialog 모달 띄움 기능
- 입력란 두 번째 항목(가격) 체크박스 만들어 선택적으로 입력 가능하게 함
- 입력란 세 번째 항목(후기) textarea 높이 자동 조절 기능
- UI 완성, 입력란 유효성 체크와 이미지 등록 기능 제외한 부가적인 기능들 완성 
- 📌 적절한 컨텐츠 ?
프로필에 pinned되는 간단한 후기들이라고 생각하여 이미지, 제목, 가격(선택사항), 후기 이렇게 구성했습니다. 라벨명이나 컨텐츠는 더 좋은 것 떠오르거나 의견 나오면 적극 반영하겠습니다!! 
- 📌 textarea, label 등에 fontfamily 임시 적용중
textarea, placeholder에 폰트패밀리 적용되지 않아 정확한 스타일을 볼 수 없어서 임시 적용중, 주석으로 표시해놨음 -> 추후 정리 필요 
- 처음 목표로 UI만 하기였는데 부가적인 기능도 겸사겸사 하게 되네요 ㅎㅎ rightIcon 불러오면 rightClick 함수 만들어야지 뭐 그런 거........ 😂
기본 화면 
늘어나면 이렇게 됩니다. 
https://user-images.githubusercontent.com/95897068/208928048-1e05a445-8f82-4b16-9ac0-71e406d35aac.mov
시연 영상 
close : #72
> 이미지 등록 UI 및 기능 구현

- .eslintrc.json
- src/App.jsx
- src/components/UserSearch/SearchedUser/index.jsx
- src/components/UserSearch/SearchedUser/index.styles.js
- src/components/UserSearch/index.jsx
- src/components/UserSearch/index.styles.js
- src/pages/Home/index.jsx
- src/pages/Search/index.jsx
- 검색 유저를 상위 5명만 보여주고 더보기 클릭 시 더 검색하는 기능 구현
- 검색된 유저 클릭 시 해당 유저의 프로필 페이지로 이동
- 검색한 내용과 동일한 username 하이라이팅
- 액박 프로필 이미지를 기본 이미지로 변경
- accountname까지 하이라이팅하니 이상해서 username만 하이라이팅되도록 했습니다. 
close : #74
> 유저 검색 페이지 기능 구현

- src/components/FollowerItem/index.jsx
- src/pages/Profile/Follower/index.jsx
- 프로필 액박 이미지 -> 후키 기본 프로필 이미지로 대체
- 언팔로우/팔로우 기능 구현
- 이얏호! 성공한 것 같습니다! 코드 보시고 리뷰 남겨주세요 😄 
close : #78
> 팔로워 페이지 팔로우/언팔로우 기능 구현

- src/components/AuthInputForm/index.jsx
- src/components/ProfileImageInput/index.jsx
- src/components/ProfileImageInput/index.style.js
- src/pages/Auth/Login/index.jsx
- src/pages/Auth/ProfileSetting/index.jsx
- src/pages/Auth/ProfileSetting/index.style.js
- src/pages/Home/index.jsx
- 회원가입 후 프로필 설정하는 페이지 기능 구현
- 프로필 이미지 누르면 이미지 설정
- 프로필 이미지 설정 후 취소하면 기본 이미지로 변경
- 아이디와 이름 입력해야 버튼 활성화 (기본 비활성화, 소개는 필수가 아니라 비어있어도 가능)
- 인풋 입력 시 유효성 검사
- 아이디: 2~16자 이내 영문, 숫자, (_), (.)
- 이름: 2~10자 이내
- 버튼 클릭 시 계정 검증
- 기존 로컬스토리지에 저장한 어카운트네임, 토큰, 이미지소스 중 이미지 소스는 제거
- 프로필 설정 후에 어카운트 네임 저장
- 로그인 완료하면 토큰 저장
- 회원가입 후에 토큰이 없는 상태라 home 페이지로 갈 수 없음, 일단 welcome 페이지로 설정
- 서버에 데이터 전송할 때 소개 입력에 개행이 포함된 값이 들어가게 작업했는데, 받을 때 어떻게 나오는지 보고 수정할 가능성(o) 
close : #76
> 프로필 페이지 설정 기능 구현

- src/App.jsx
- src/api/profile.js
- src/components/Post/PostItem/index.jsx
- src/components/Post/PostList/index.jsx
- src/components/Profile/UserInfo/index.jsx
- src/components/Profile/UserInfo/index.styles.js
- src/components/common/Navigation/index.jsx
- src/pages/Home/index.styles.js
- src/pages/Profile/index.jsx
- src/pages/Profile/index.styles.js
- 피그마 디자인에 맞춰 section 사이를 light_gray 색상으로 추가했는데 , 저 색상이 의도된걸까요? 일단 보이는대로 구현했습니다.
나의 페이지, 포스트 없을때 (이전 스샷이라 위에 앨범형, 리스트형 없음)
나의 페이지, 포스트 있을 때
팔로우 안되있는 계정(test@gmail.com로 본 화면)
팔로우 되있는 계정(test@gmail.com로 본 화면)
close : #89
> 프로필 페이지 UI 구현

- src/App.jsx
- src/api/follow.js
- src/api/post.js
- src/components/Post/AlbumPostItem/index.jsx
- src/components/Post/AlbumPostItem/index.styles.js
- src/components/Post/PostList/index.jsx
- src/components/Post/PostList/index.styles.js
- src/components/Profile/ProfilePost/index.jsx
- src/components/Profile/ProfilePost/index.styles.js
- src/components/Profile/UserInfo/index.jsx
- src/pages/Home/index.jsx
- src/pages/Post/PostEdit/index.jsx
- src/pages/Post/PostUpload/index.jsx
- src/pages/Profile/Follower/index.jsx
- src/pages/Profile/index.jsx
- 앨범형 아이템 세로 길이를 고정했기 때문에 화면이 커질 경우 대응 불가능 (해결 못했습니다..)
- 다크모드, 로그아웃, 프로필 수정, 팔로잉 목록 페이지 작업 필요
- chat 페이지에서 뒤로가기시 홈으로 고정된 것 수정 필요
나의 프로필 페이지
타인의 프로필 페이지
close : #94
> 프로필 페이지 기능 구현

- .eslintrc.json
- src/atoms/profileInfo.js
- src/components/AuthInputForm/index.jsx
- src/components/Profile/ProfileInfoForm/index.jsx
- src/components/Profile/ProfileInfoForm/index.styles.js
- src/components/Profile/UserInfo/index.jsx
- src/components/ProfileImageInput/index.jsx
- src/components/common/ConfirmHeader/index.jsx
- src/pages/Auth/ProfileSetting/index.jsx
- src/pages/Auth/ProfileSetting/index.style.js
- src/pages/Auth/SignUp/index.jsx
- src/pages/Profile/ProfileEdit/index.jsx
- src/pages/Profile/ProfileEdit/index.styles.js
- 간혈적으로 프로필 세팅이나 프로필 수정에서 이미지를 변경하고 완료를 눌러도 이미지가 변경되지 않는 현상이 발생합니다. 
- isLoading이나 try catch로 잡아야할 듯 합니다 
close : #99
> 프로필 세팅 페이지 UI, 기능 구현

- src/components/Profile/UserInfo/index.jsx
- src/index.jsx
- 구분 되는 데이터를 react-query로 불러오는 경우, 각자 고유한 키를 줍시다..!
close : #123
> 프로필 이동 시 내 프로필로 돌아와도 내 프로필로 변하지 않는 현상 해결

- src/api/authAxios.js
- src/components/AuthInputForm/index.jsx
- src/components/Profile/ProfileInfoForm/index.jsx
- src/components/Profile/UserInfo/index.styles.js
- src/components/ProfileImageInput/index.jsx
- src/components/ProfileImageInput/index.style.js
- src/pages/Profile/ProfileEdit/index.jsx
> 프로필 수정에서 accountName을 변경할 수 없도록 수정, 프로필 수정 코드 리팩토링

- src/pages/Auth/SignUp/index.jsx
- 의존성 배열 값이 `buttonNotAllow`로만 설정되어있었는데 `hookie17@gmail.com`에서 7을 지운 뒤 어떠한 값을 입력하거나 지워도 buttonNotAllow의 불리언 값의 변화가 한번만 일어나게 됩니다.
아래 사진과 같이 이렇게 의도와 다른 값이 전달되어 발생한 에러
기존 `hookie1@gmail.com` 이메일이 가입되어있던 상태라 `hookie18@gmail.com`을 입력해도 `hookie1@gmail.com`의 값이 전달 되기 때문
- `handleJoinClick()` useCallback의 Dependency array의 값으로 인한 에러
close : #132
> 유효성 검사 후 가입하지 않은 이메일임에도 가입 되었다는 오류

- src/components/Profile/ProfilePost/index.jsx
- src/components/Profile/UserInfo/index.jsx
1. 내가 내 프로필에서 홈페이지로 이동할때
1. 내가 내 프로필로 이동 => myPostList 쿼리 키에 나의 data가 등록됨
2. 홈페이지로 이동 
1. myPostList 쿼리 키에 나의 data가 등록됨
2. followPostList 쿼리 키에 나의 팔로워 피드가 등록됨 
2. 내가 다른 사람 프로필에서 홈페이지로 이동할때
1. 내가 다른 사람 프로필로 이동 => myPostList 쿼리 키에 해당 유저의 data가 등록됨
2. 홈페이지로 이동
1. myPostList 쿼리 키에 나의 data가 등록됨 
1. 이전 캐시된 데이터(다른 사람 프로필에서 저장된 해당 유저의 feed data)와 나의 feed data가 모두 불려와짐 
2. followPostList 쿼리 키에 나의 팔로워 피드가 등록됨
때문에 follower의 게시글이 두번 불려와져서 문제가 발생
=> 프로필 페이지의 쿼리키를 분리하여 해결
close : #136
> 다른 팔로워의 프로필 페이지에서 홈페이지로 이동하면 발생하는 키에러 수정

- src/components/FollowItem/index.jsx
- src/components/FollowItem/index.styles.js
- src/pages/Profile/Follower/index.jsx
- src/pages/Profile/Follower/index.styles.js
- src/pages/Profile/Following/index.jsx
- src/pages/Profile/Following/index.styles.js
> 팔로워/팔로잉 페이지 스타일 분리 및 오류 수정

- src/api/comment.js
댓글 갯수가 원래는 최신 댓글 기준으로 10개까지만 보였는데, 이제는 처음부터 끝까지 다 보입니다!
close : #185
> 게시글 상세 페이지 모든 댓글이 보이도록 구현

- src/components/Post/PostItem/index.jsx
- 다른 프로젝트에서 만든 계정의 글을 불러올 수 있습니다.
- 다른 프로젝트의 이미지는 해당 프로젝트의 처리에 따라 보이는 것과 안보이는 것이 있습니다.
close : #189
> 다른 프로젝트의 계정의 글에 접근할 경우 발생하는 에러 해결
